### ISSUE TITLE
Wikimedia functions highly fragmented across 4+ packages 

### ISSUE THREAD

**Issue by jeremiahpslewis** [Ironholds/pageviews#9]
What are your thoughts about the value to be had in merging together the set of related packages mentioned in this post: http://jlewis91.github.io/Wikipedia-Pageviews/ ?

Feel like there is a ton of overlap in functionality and lots of potential for using this set of related functions in complementary ways. Both from a maintenance perspective (all packages are basically API wrappers, so feature creep ought to be kept to a minimum), and there would be the added benefit that a user, interested in one facet of the wikipedia data, might then easily go on to try out another aspect.

Furthermore having such a high degree of fragmentation limits visibility as well as limiting coding best practices (not all packages have tests, are set up for CI, etc.). Just want to gauge your level of support (as author of three separate Wikimedia packages) before forking a bunch of stuff and pushing this forward.

**Comment by Ironholds** [comment]
I feel like we could certainly merge WikipediR and WikidataR together, but pageviews are distinct enough we might want them to be their own thing. If you can point out functionality in the other WP package that is missing here I would love to incorporate it!

Also on a more ornery note I'll be damned if I'm taking GPL-licensing on for my package ;p.

**Comment by petermeissner** [comment]
I finally had time to take a look at the pageviews package. Actually, I thought about deprecating my package and making it a simple wrapper around the pageviews package to allow wikipediatrend package users to run their already written scripts but still benefit from the NEW API. 

A problem with the new API I found though, is that it is not really filled with that much data (yet?) and often I got 400 or 404 errors. So, connecting to both APIs still has its merits. 

**features in wikipediatrend but not in pageviews:** 
- caching 
- getting titles / page views for articles in other languages

**In regard to consolidating packages:** 
- I think page view data and Wikipedia data should be kept separate.
- Putting together the pageviews package and the wikipediatrend package might be an option (though I think I have the better name and I think my function parameters are more fun to type in - I am still a little fuzzy from reading and typing things like "2015010100" :-) )
- my GPL Licencing comes from reusing R-Core source code which might be circumvented
- though I am not 100% convinced that consolidating wikipediatrend and pageviews is really necessary 
  I am open for discussion

**Idea:** 
- instead of making one package out of pageviews and wikipediatrend I think it might be a good idea to add another package called statsgrokse which would parallel pageviews in the regard that it would be build close to the stats.grok.se API while wikipediatrend then would be free as an meta package that wraps around pageviews and statsgrokse allowing for a unified user experience and data comming from both sources 
- discuss!

**Comment by Ironholds** [comment]
I really like that idea! I am not, as previously discussed, actively developing right now though :(

**Comment by petermeissner** [comment]
That is still a pity. 
I keep the general idea in mind and maybe I have some time in the months to come.

**Comment by petermeissner** [comment]
see also here: https://github.com/petermeissner/wikipediatrend/issues/29

**Comment by petermeissner** [comment]
From Version 2.x.x wikipediatrend uses the new API as data source (which provides data from mid 2015 onwards).
